/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PlayFair;

/**
 *
 * @author Administrator
 */
public class jPlayFair extends javax.swing.JFrame {
    char pf[][] = {{'M','O','N','A','R'},
                    {'C','H','Y','B','D'},
                    {'E','F','G','I','K'},
                    {'L','P','Q','S','T'},
                    {'U','V','W','X','Z'}
    };
    /**
     * Creates new form jPlayFair
     */
    public jPlayFair() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtBanRo = new javax.swing.JTextField();
        txtKhoa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtBanMa = new javax.swing.JTextArea();
        btnMaHoa = new javax.swing.JButton();
        btnGiaiMa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ban ro");

        jLabel2.setText("Khoa");

        jLabel3.setText("Ban ma");

        txtBanRo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBanRoActionPerformed(evt);
            }
        });

        txtKhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKhoaActionPerformed(evt);
            }
        });

        txtBanMa.setColumns(20);
        txtBanMa.setRows(5);
        jScrollPane1.setViewportView(txtBanMa);

        btnMaHoa.setText("Ma hoa");
        btnMaHoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaHoaActionPerformed(evt);
            }
        });

        btnGiaiMa.setText("Giai ma");
        btnGiaiMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiaiMaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMaHoa)
                        .addGap(29, 29, 29)
                        .addComponent(btnGiaiMa))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtBanRo)
                        .addComponent(txtKhoa)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBanRo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMaHoa)
                    .addComponent(btnGiaiMa))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBanRoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBanRoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBanRoActionPerformed

    private void txtKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKhoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKhoaActionPerformed

    private void btnMaHoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaHoaActionPerformed
        // TODO add your handling code here:
        String banro = this.txtBanRo.getText();
        banro = banro.toUpperCase();
        banro = banro.replace('J', 'I');
        String banma = mahoa(banro);
        this.txtBanMa.setText(banma);
    }//GEN-LAST:event_btnMaHoaActionPerformed

    private void btnGiaiMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiaiMaActionPerformed
        // TODO add your handling code here:
        String banma = this.txtBanMa.getText();
        String banro = giaima(banma);
        int n = banro.length();
        String br = "";
        for(int i=0;i<n-2;i+=2){
            if(banro.charAt(i)==banro.charAt(i+2))
                br+=banro.charAt(i);
            else
                br+=banro.charAt(i)+ "" + banro.charAt(i+1);
        }
        if(banro.charAt(n-1)=='X')
            br+=banro.charAt(n-2);
        else
            br+=banro.charAt(n-2);  br+=banro.charAt(n-1);
        this.txtBanRo.setText(br);     
    }//GEN-LAST:event_btnGiaiMaActionPerformed
    // giai ma
    private String giaima(String banma) {
        int n = banma.length();
        String banro = "";
        char a, b;
        for(int i=0;i<n;i+=2){
            a=banma.charAt(i);
            b=banma.charAt(i+1);
            banro+=thayTheNguoc(a,b);
        }
        return banro;
    }
    String thayTheNguoc(char a, char b){
        String vta = timViTri(a);
        String vtb = timViTri(b);
        char x,y;
        if(vta.charAt(0)==vtb.charAt(0)){
            x = pf[vta.charAt(0)-'0'][((vta.charAt(1)-'0')-1+5)%5];
            y = pf[vtb.charAt(0)-'0'][((vtb.charAt(1)-'0')-1+5)%5];
            return x+""+y;
        }
        if(vta.charAt(1)==vtb.charAt(1)){
            x = pf[((vta.charAt(0)-'0')-1+5)%5][(vta.charAt(1)-'0')];
            y = pf[((vtb.charAt(0)-'0')-1+5)%5][(vtb.charAt(1)-'0')];
            return x+""+y;
        }
        x = pf[vta.charAt(0)-'0'][(vtb.charAt(1)-'0')];
        y = pf[vtb.charAt(0)-'0'][(vta.charAt(1)-'0')];
        return x+""+y;
    }
    private String mahoa(String banro) {
        int n = banro.length(); 
        int i = 0;
        String banma = "";
        char a,b;
        while(i<n) {
            if(i==n-1) {
                a = banro.charAt(i);
                b = 'X';
                i++;
            } else {
                a = banro.charAt(i);
                b = banro.charAt(i + 1);
                if(a==b) {
                    b = 'X';
                    i++; 
                } else 
                    i+=2;
            }
            banma+=thayThe(a,b);
        }
        return banma;
    }
    String thayThe(char a, char b) {
        String vta = timViTri(a);
        String vtb = timViTri(b);
        char x,y;
        if(vta.charAt(0)==vtb.charAt(0)){
            x = pf[vta.charAt(0)-'0'][((vta.charAt(1)-'0')+1)%5];
            y = pf[vtb.charAt(0)-'0'][((vtb.charAt(1)-'0')+1)%5];
            return x+""+y;
        }
        if(vta.charAt(1)==vtb.charAt(1)){
            x = pf[((vta.charAt(0)-'0')+1)%5][(vta.charAt(1)-'0')];
            y = pf[((vtb.charAt(0)-'0')+1)%5][(vtb.charAt(1)-'0')];
            return x+""+y;
        }
        x = pf[vta.charAt(0)-'0'][(vtb.charAt(1)-'0')];
        y = pf[vtb.charAt(0)-'0'][(vta.charAt(1)-'0')];
        return x+""+y;
    }
    private String timViTri(char a) {
        for(int i=0;i<5;i++){
            for(int j=0;j<5;j++){
                if(pf[i][j]==a)
                    return i+""+j;
            }
        }
        return "";
    }
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jPlayFair.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jPlayFair.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jPlayFair.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jPlayFair.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jPlayFair().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGiaiMa;
    private javax.swing.JButton btnMaHoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtBanMa;
    private javax.swing.JTextField txtBanRo;
    private javax.swing.JTextField txtKhoa;
    // End of variables declaration//GEN-END:variables
}
